
module.exports = [
    {short:"  " , name:"Please select a country"},
    {short:"AU" , name:"Australia"},
    {short:"BZ" , name:"Belize"},
    {short:"CN" , name:"China"},
    {short:"FR" , name:"France"},
    {short:"DE" , name:"Germany"},
    {short:"HK" , name:"Hong Kong"},
    {short:"IN" , name:"India"},
    {short:"JP" , name:"Japan"},
    {short:"NZ" , name:"New Zealand"},
    {short:"PH" , name:"Philippines"},
    {short:"SG" , name:"Singapore"},
    {short:"ZA" , name:"South Africa"},
    {short:"ES" , name:"Spain"},
    {short:"TW" , name:"Taiwan"},
    {short:"TH" , name:"Thailand"},
    {short:"GB" , name:"United Kingdom"},
    {short:"US" , name:"United States"},
]